apiVersion: apps/v1
kind: Deployment
metadata:
  name: djcova
  namespace: starbunk
  labels:
    app: djcova
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djcova
  template:
    metadata:
      labels:
        app: djcova
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      containers:
        - name: djcova
          image: us-central1-docker.pkg.dev/starbunk-bot/starbunk-repo/starbunk-djcova:latest
          imagePullPolicy: Always
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: starbunk-secrets
                  key: DJCOVA_TOKEN
            - name: RUST_LOG
              value: "info"
            - name: VERBOSE
              value: "false"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: YOUTUBE_COOKIES_PATH
              value: "/etc/cookies/youtube.txt"
          volumeMounts:
            - name: cookies-volume
              mountPath: "/etc/cookies"
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: cookies-volume
          secret:
            secretName: youtube-cookies
