apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-serve-config
  namespace: starbunk
data:
  serve-config.json: |
    {
      "TCP": {
        "443": {
          "HTTPS": true
        },
        "80": {
          "HTTPS": false
        }
      },
      "Web": {
        "${TS_CERT_DOMAIN}:443": {
          "Handlers": {
            "/": {
              "Proxy": "http://127.0.0.1:3000"
            }
          }
        },
        "${TS_CERT_DOMAIN}:80": {
          "Handlers": {
            "/": {
              "Proxy": "http://127.0.0.1:3000"
            }
          }
        }
      },
      "AllowFunnel": {
        "${TS_CERT_DOMAIN}:443": false,
        "${TS_CERT_DOMAIN}:80": false
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-proxy-pvc
  namespace: starbunk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
